spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/sns_project
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.default_batch_fetch_size: 1000    #batch size설정해서 n + 1 문제 해결
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue: notification_queue
    exchange: notification_exchange
    routing_key: notification_key
  cache:
    type: caffeine   #caffeine 캐시 설정
    caffeine:
      spec: maximumSize=500,expireAfterWrite=600s

  notification:
    broker: rabbitmq

redis:
  host: localhost
  port: 6379

#prometheus 설정
management:
  endpoints:
    web:
      exposure:
        include: prometheus


logging:
  config: classpath:logback-spring-local.xml
  level:
    org:
      hibernate:
        SQL : DEBUG
        type:
          descriptor:
            sql: trace

#로컬에 이미지 저장 설정.
file:
  storage-type: local
  profile-images-dir: ./uploads/profile_images
  posting-images-dir: ./uploads/posting_images

jwt:
  secret: secretKey-for-authorization-jwtToken
  expiration: 3600000             #60 * 60 * 1000
  refreshExpiration : 86400000    #expiration * 24

sse:
  timeout: 3600000  #60 * 60 * 1000


